plugins:
  calendar_enabled:
    default: false
    client: true
  holiday_calendar_topic_id:
    default: ""
    client: true
  delete_expired_event_posts_after:
    min: -1
    default: 1
  all_day_event_start_time:
    default: ""
    client: true
    validator: "CalendarSettingsValidator"
  all_day_event_end_time:
    default: ""
    client: true
    validator: "CalendarSettingsValidator"

